export const events = [
  {
    image: '/images/event1.png',
    title: 'Next.js Conf 2025',
    slug: 'nextjs-conf-2025',
    location: 'San Francisco, CA, USA',
    date: '2025-12-10',
    time: '09:00 AM',
  },
  {
    image: '/images/event2.png',
    title: 'Europe Dev Hackathon',
    slug: 'europe-dev-hackathon',
    location: 'Berlin, Germany',
    date: '2026-01-15',
    time: '10:00 AM',
  },
  {
    image: '/images/event3.png',
    title: 'JS World Conference',
    slug: 'js-world-conference',
    location: 'Amsterdam, Netherlands',
    date: '2026-02-20',
    time: '08:30 AM',
  },
  {
    image: '/images/event3.png',
    title: 'PyCon Global 2026',
    slug: 'pycon-global-2026',
    location: 'Virtual',
    date: '2026-03-05',
    time: 'All Day',
  },
  {
    image: '/images/event4.png',
    title: 'Google DevFest',
    slug: 'google-devfest',
    location: 'London, UK',
    date: '2025-12-01',
    time: '11:00 AM',
  },
  {
    image: '/images/event5.png',
    title: 'React Summit',
    slug: 'react-summit',
    location: 'New York, NY, USA',
    date: '2026-04-12',
    time: '09:30 AM',
  },
];